### ISSUE TITLE
Cannot open /explorer 

### ISSUE THREAD

**Issue by jaeko44** [asaf050/loopback-pkg-ready#1]
Error
404 Cannot GET /explorer/
status: 404
Error: Cannot GET /explorer/
    at raiseUrlNotFoundError (B:\snapshot\loopback-pkg-ready-master\node_modules\loopback\server\middleware\url-not-found.js:0:0)

Any idea?

**Comment by jaeko44** [comment]
/api still works however, so it's still functional which is great 👍

**Comment by asaf050** [comment]
Hey @jaeko44 , I push a fix. Only need to add some paths to package.json file.
Can you please verify the fix?

**Comment by jaeko44** [comment]
@asaf050 Thank you, it works now 👍
